pipeline {
    agent any  // Run on any available agent

    environment {
        PLAYWRIGHT_BROWSERS_PATH = "E:\1_Web Automation\PLAYWRIGHT\Playwright-test-automation1\chrome\chromedrive.exe"  // Path for browsers
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing Node.js dependencies...'
                sh 'npm install'
            }
        }

        stage('Install Playwright Browsers') {
            steps {
                echo 'Installing Playwright browsers...'
                sh 'npx playwright install'
            }
        }

        stage('Run Playwright Tests') {
            steps {
                echo 'Executing Playwright tests...'
                sh 'npx playwright test'
            }
        }

        stage('Publish Test Reports') {
            steps {
                echo 'Publishing Playwright HTML report...'
                sh 'npx playwright show-report'
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed!'
        }
    }
}
